//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvEtrBus.srvLotusClients {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.0.77:8080/IMPR/TasWebDB.nsf", ConfigurationName="srvLotusClients.agentSrv")]
    public interface agentSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GETCLIENTBYPHONEReturn")]
        string GETCLIENTBYPHONE(string SPHONE);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GETCLIENTBYPHONEReturn")]
        System.Threading.Tasks.Task<string> GETCLIENTBYPHONEAsync(string SPHONE);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface agentSrvChannel : srvEtrBus.srvLotusClients.agentSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class agentSrvClient : System.ServiceModel.ClientBase<srvEtrBus.srvLotusClients.agentSrv>, srvEtrBus.srvLotusClients.agentSrv {
        
        public agentSrvClient() {
        }
        
        public agentSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public agentSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public agentSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public agentSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GETCLIENTBYPHONE(string SPHONE) {
            return base.Channel.GETCLIENTBYPHONE(SPHONE);
        }
        
        public System.Threading.Tasks.Task<string> GETCLIENTBYPHONEAsync(string SPHONE) {
            return base.Channel.GETCLIENTBYPHONEAsync(SPHONE);
        }
    }
}
